// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v7.35.1
// source: src/common/internal-protobuf/settings.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";

/** _Read_ receipt policy (when an unread message has been read) */
export const ReadReceiptPolicy = {
  /** SEND_READ_RECEIPT - Send _read_ receipt when an unread message has been read */
  SEND_READ_RECEIPT: 0,
  /** DONT_SEND_READ_RECEIPT - Don't send _read_ receipts */
  DONT_SEND_READ_RECEIPT: 1,
  UNRECOGNIZED: -1,
} as const;

export type ReadReceiptPolicy = typeof ReadReceiptPolicy[keyof typeof ReadReceiptPolicy];

export namespace ReadReceiptPolicy {
  export type SEND_READ_RECEIPT = typeof ReadReceiptPolicy.SEND_READ_RECEIPT;
  export type DONT_SEND_READ_RECEIPT = typeof ReadReceiptPolicy.DONT_SEND_READ_RECEIPT;
  export type UNRECOGNIZED = typeof ReadReceiptPolicy.UNRECOGNIZED;
}

/** Typing indicator policy (signal _currently typing_) */
export const TypingIndicatorPolicy = {
  /** SEND_TYPING_INDICATOR - Send _typing_ indicator when a message is being composed */
  SEND_TYPING_INDICATOR: 0,
  /** DONT_SEND_TYPING_INDICATOR - Don't send _typing_ indicators */
  DONT_SEND_TYPING_INDICATOR: 1,
  UNRECOGNIZED: -1,
} as const;

export type TypingIndicatorPolicy = typeof TypingIndicatorPolicy[keyof typeof TypingIndicatorPolicy];

export namespace TypingIndicatorPolicy {
  export type SEND_TYPING_INDICATOR = typeof TypingIndicatorPolicy.SEND_TYPING_INDICATOR;
  export type DONT_SEND_TYPING_INDICATOR = typeof TypingIndicatorPolicy.DONT_SEND_TYPING_INDICATOR;
  export type UNRECOGNIZED = typeof TypingIndicatorPolicy.UNRECOGNIZED;
}

export interface Unit {
}

/** Container for a list of identities */
export interface Identities {
  /** List of identities */
  identities: string[];
}

/** Profile settings */
export interface ProfileSettings {
  /** Nickname */
  nickname?:
    | string
    | undefined;
  /** Profile picture blob */
  profilePictureBlob?:
    | Uint8Array
    | undefined;
  /** Profile picture blobID */
  profilePictureBlobId?:
    | Uint8Array
    | undefined;
  /** The date the profile picture was last uploaded to the server */
  profilePictureLastUploadedAt?:
    | Long
    | undefined;
  /** The symmetric key of the current profile picture */
  profilePictureKey?: Uint8Array | undefined;
  profilePictureShareWith?: ProfileSettings_ProfilePictureShareWith | undefined;
  workAvailabilityStatus?: ProfileSettings_WorkAvailabilityStatus | undefined;
}

export interface ProfileSettings_ProfilePictureShareWith {
  policy?:
    | //
    /** Don't share */
    { $case: "nobody"; nobody: Unit }
    | //
    /** Share with everyone */
    { $case: "everyone"; everyone: Unit }
    | //
    /**
     * Share only with explicitly listed contacts
     *
     * When the user selected _allow list_ but did not select any contacts,
     * send an empty list. Do not fall back to `nobody`.
     */
    { $case: "allowList"; allowList: Identities }
    | undefined;
}

export interface ProfileSettings_WorkAvailabilityStatus {
  category: ProfileSettings_WorkAvailabilityStatus_Category;
  description?: string | undefined;
}

export const ProfileSettings_WorkAvailabilityStatus_Category = {
  NONE: 0,
  UNAVAILABLE: 1,
  BUSY: 2,
  UNRECOGNIZED: -1,
} as const;

export type ProfileSettings_WorkAvailabilityStatus_Category =
  typeof ProfileSettings_WorkAvailabilityStatus_Category[keyof typeof ProfileSettings_WorkAvailabilityStatus_Category];

export namespace ProfileSettings_WorkAvailabilityStatus_Category {
  export type NONE = typeof ProfileSettings_WorkAvailabilityStatus_Category.NONE;
  export type UNAVAILABLE = typeof ProfileSettings_WorkAvailabilityStatus_Category.UNAVAILABLE;
  export type BUSY = typeof ProfileSettings_WorkAvailabilityStatus_Category.BUSY;
  export type UNRECOGNIZED = typeof ProfileSettings_WorkAvailabilityStatus_Category.UNRECOGNIZED;
}

/** Privacy settings */
export interface PrivacySettings {
  contactSyncPolicy?: PrivacySettings_ContactSyncPolicy | undefined;
  unknownContactPolicy?:
    | PrivacySettings_UnknownContactPolicy
    | undefined;
  /**
   * _Read_ receipt policy (when an unread message has been read)
   *
   * Required towards a new device. Optional otherwise.
   */
  readReceiptPolicy?:
    | ReadReceiptPolicy
    | undefined;
  /**
   * Typing indicator policy (signal _currently typing_)
   *
   * Required towards a new device. Optional otherwise.
   */
  typingIndicatorPolicy?: TypingIndicatorPolicy | undefined;
  screenshotPolicy?: PrivacySettings_ScreenshotPolicy | undefined;
  keyboardDataCollectionPolicy?:
    | PrivacySettings_KeyboardDataCollectionPolicy
    | undefined;
  /**
   * List of Threema IDs whose messages are blocked
   *
   * Required towards a new device. Optional otherwise.
   *
   * An empty list is valid.
   */
  blockedIdentities:
    | Identities
    | undefined;
  /**
   * Threema IDs to be excluded when syncing the contact list
   *
   * Required towards a new device. Optional otherwise.
   *
   * An empty list is valid.
   */
  excludeFromSyncIdentities: Identities | undefined;
}

/**
 * Contact synchronisation policy
 *
 * Required towards a new device. Optional otherwise.
 */
export const PrivacySettings_ContactSyncPolicy = {
  /** NOT_SYNCED - Not synced */
  NOT_SYNCED: 0,
  /** SYNC - Synced */
  SYNC: 1,
  UNRECOGNIZED: -1,
} as const;

export type PrivacySettings_ContactSyncPolicy =
  typeof PrivacySettings_ContactSyncPolicy[keyof typeof PrivacySettings_ContactSyncPolicy];

export namespace PrivacySettings_ContactSyncPolicy {
  export type NOT_SYNCED = typeof PrivacySettings_ContactSyncPolicy.NOT_SYNCED;
  export type SYNC = typeof PrivacySettings_ContactSyncPolicy.SYNC;
  export type UNRECOGNIZED = typeof PrivacySettings_ContactSyncPolicy.UNRECOGNIZED;
}

/**
 * Unknown contacts policy
 *
 * Required towards a new device. Optional otherwise.
 */
export const PrivacySettings_UnknownContactPolicy = {
  /** ALLOW_UNKNOWN - Allowed to contact the user */
  ALLOW_UNKNOWN: 0,
  /** BLOCK_UNKNOWN - Will be blocked by the user */
  BLOCK_UNKNOWN: 1,
  UNRECOGNIZED: -1,
} as const;

export type PrivacySettings_UnknownContactPolicy =
  typeof PrivacySettings_UnknownContactPolicy[keyof typeof PrivacySettings_UnknownContactPolicy];

export namespace PrivacySettings_UnknownContactPolicy {
  export type ALLOW_UNKNOWN = typeof PrivacySettings_UnknownContactPolicy.ALLOW_UNKNOWN;
  export type BLOCK_UNKNOWN = typeof PrivacySettings_UnknownContactPolicy.BLOCK_UNKNOWN;
  export type UNRECOGNIZED = typeof PrivacySettings_UnknownContactPolicy.UNRECOGNIZED;
}

/**
 * Screenshot policy
 *
 * Required towards a new device. Optional otherwise.
 */
export const PrivacySettings_ScreenshotPolicy = {
  /** ALLOW_SCREENSHOT - Allow taking screenshots */
  ALLOW_SCREENSHOT: 0,
  /** DENY_SCREENSHOT - Deny taking screenshots, if possible */
  DENY_SCREENSHOT: 1,
  UNRECOGNIZED: -1,
} as const;

export type PrivacySettings_ScreenshotPolicy =
  typeof PrivacySettings_ScreenshotPolicy[keyof typeof PrivacySettings_ScreenshotPolicy];

export namespace PrivacySettings_ScreenshotPolicy {
  export type ALLOW_SCREENSHOT = typeof PrivacySettings_ScreenshotPolicy.ALLOW_SCREENSHOT;
  export type DENY_SCREENSHOT = typeof PrivacySettings_ScreenshotPolicy.DENY_SCREENSHOT;
  export type UNRECOGNIZED = typeof PrivacySettings_ScreenshotPolicy.UNRECOGNIZED;
}

/**
 * Keyboard data collection policy (e.g. for personalised suggestions)
 *
 * Required towards a new device. Optional otherwise.
 */
export const PrivacySettings_KeyboardDataCollectionPolicy = {
  /** ALLOW_DATA_COLLECTION - Allow keyboard input data to be collected */
  ALLOW_DATA_COLLECTION: 0,
  /** DENY_DATA_COLLECTION - Deny collecting of keyboard input data */
  DENY_DATA_COLLECTION: 1,
  UNRECOGNIZED: -1,
} as const;

export type PrivacySettings_KeyboardDataCollectionPolicy =
  typeof PrivacySettings_KeyboardDataCollectionPolicy[keyof typeof PrivacySettings_KeyboardDataCollectionPolicy];

export namespace PrivacySettings_KeyboardDataCollectionPolicy {
  export type ALLOW_DATA_COLLECTION = typeof PrivacySettings_KeyboardDataCollectionPolicy.ALLOW_DATA_COLLECTION;
  export type DENY_DATA_COLLECTION = typeof PrivacySettings_KeyboardDataCollectionPolicy.DENY_DATA_COLLECTION;
  export type UNRECOGNIZED = typeof PrivacySettings_KeyboardDataCollectionPolicy.UNRECOGNIZED;
}

/** Calls settings */
export interface CallsSettings {
  o2oCallPolicy?: CallsSettings_O2oCallPolicy | undefined;
  o2oCallConnectionPolicy?: CallsSettings_O2oCallConnectionPolicy | undefined;
  groupCallPolicy?:
    | CallsSettings_GroupCallPolicy
    | undefined;
  /** The name of the most recently selected camera device */
  lastSelectedCamera?:
    | string
    | undefined;
  /** The name of the most recently selected microphone device */
  lastSelectedMicrophone?:
    | string
    | undefined;
  /** The name of the most recently selected speaker device */
  lastSelectedSpeakers?: string | undefined;
}

/**
 * Threema Call policy
 *
 * Required towards a new device. Optional otherwise.
 */
export const CallsSettings_O2oCallPolicy = {
  /** ALLOW_CALL - Allow creating/receiving Threema Calls */
  ALLOW_CALL: 0,
  /** DENY_CALL - Denied from creating/receiving any Threema Calls */
  DENY_CALL: 1,
  UNRECOGNIZED: -1,
} as const;

export type CallsSettings_O2oCallPolicy = typeof CallsSettings_O2oCallPolicy[keyof typeof CallsSettings_O2oCallPolicy];

export namespace CallsSettings_O2oCallPolicy {
  export type ALLOW_CALL = typeof CallsSettings_O2oCallPolicy.ALLOW_CALL;
  export type DENY_CALL = typeof CallsSettings_O2oCallPolicy.DENY_CALL;
  export type UNRECOGNIZED = typeof CallsSettings_O2oCallPolicy.UNRECOGNIZED;
}

/**
 * Threema Call connection policy
 *
 * Required towards a new device. Optional otherwise.
 */
export const CallsSettings_O2oCallConnectionPolicy = {
  /** ALLOW_DIRECT - Allow direct (peer-to-peer) connections for Threema Calls */
  ALLOW_DIRECT: 0,
  /** REQUIRE_RELAY - Require relayed connections for Threema Calls */
  REQUIRE_RELAY: 1,
  UNRECOGNIZED: -1,
} as const;

export type CallsSettings_O2oCallConnectionPolicy =
  typeof CallsSettings_O2oCallConnectionPolicy[keyof typeof CallsSettings_O2oCallConnectionPolicy];

export namespace CallsSettings_O2oCallConnectionPolicy {
  export type ALLOW_DIRECT = typeof CallsSettings_O2oCallConnectionPolicy.ALLOW_DIRECT;
  export type REQUIRE_RELAY = typeof CallsSettings_O2oCallConnectionPolicy.REQUIRE_RELAY;
  export type UNRECOGNIZED = typeof CallsSettings_O2oCallConnectionPolicy.UNRECOGNIZED;
}

/**
 * Threema Group Call policy
 *
 * Required towards a new device. Optional otherwise.
 */
export const CallsSettings_GroupCallPolicy = {
  /** ALLOW_GROUP_CALL - Allow creating/receiving Threema Group Calls */
  ALLOW_GROUP_CALL: 0,
  /** DENY_GROUP_CALL - Denied from creating/receiving any Threema Group Calls */
  DENY_GROUP_CALL: 1,
  UNRECOGNIZED: -1,
} as const;

export type CallsSettings_GroupCallPolicy =
  typeof CallsSettings_GroupCallPolicy[keyof typeof CallsSettings_GroupCallPolicy];

export namespace CallsSettings_GroupCallPolicy {
  export type ALLOW_GROUP_CALL = typeof CallsSettings_GroupCallPolicy.ALLOW_GROUP_CALL;
  export type DENY_GROUP_CALL = typeof CallsSettings_GroupCallPolicy.DENY_GROUP_CALL;
  export type UNRECOGNIZED = typeof CallsSettings_GroupCallPolicy.UNRECOGNIZED;
}

/** Devices Settings */
export interface DevicesSettings {
  /** The name of the local device */
  deviceName?: string | undefined;
}

/** Appearance Settings */
export interface AppearanceSettings {
  timeFormat?: AppearanceSettings_TimeFormat | undefined;
  inactiveContactsPolicy?: AppearanceSettings_HideInactive | undefined;
}

/** Time format (12h vs 24h display) */
export const AppearanceSettings_TimeFormat = { TIME_24H: 0, TIME_12H: 1, UNRECOGNIZED: -1 } as const;

export type AppearanceSettings_TimeFormat =
  typeof AppearanceSettings_TimeFormat[keyof typeof AppearanceSettings_TimeFormat];

export namespace AppearanceSettings_TimeFormat {
  export type TIME_24H = typeof AppearanceSettings_TimeFormat.TIME_24H;
  export type TIME_12H = typeof AppearanceSettings_TimeFormat.TIME_12H;
  export type UNRECOGNIZED = typeof AppearanceSettings_TimeFormat.UNRECOGNIZED;
}

/** Whether to show or hide inactive contacts */
export const AppearanceSettings_HideInactive = { SHOW: 0, HIDE: 1, UNRECOGNIZED: -1 } as const;

export type AppearanceSettings_HideInactive =
  typeof AppearanceSettings_HideInactive[keyof typeof AppearanceSettings_HideInactive];

export namespace AppearanceSettings_HideInactive {
  export type SHOW = typeof AppearanceSettings_HideInactive.SHOW;
  export type HIDE = typeof AppearanceSettings_HideInactive.HIDE;
  export type UNRECOGNIZED = typeof AppearanceSettings_HideInactive.UNRECOGNIZED;
}

/** Media Settings */
export interface MediaSettings {
  autoDownload?: MediaSettings_AutoDownload | undefined;
  animatedImageMode?: MediaSettings_AnimatedImageMode | undefined;
  videoQuality?: MediaSettings_VideoQuality | undefined;
}

/** Whether or not to loop animated images. */
export const MediaSettings_AnimatedImageMode = { LOOP: 0, DONT_LOOP: 1, UNRECOGNIZED: -1 } as const;

export type MediaSettings_AnimatedImageMode =
  typeof MediaSettings_AnimatedImageMode[keyof typeof MediaSettings_AnimatedImageMode];

export namespace MediaSettings_AnimatedImageMode {
  export type LOOP = typeof MediaSettings_AnimatedImageMode.LOOP;
  export type DONT_LOOP = typeof MediaSettings_AnimatedImageMode.DONT_LOOP;
  export type UNRECOGNIZED = typeof MediaSettings_AnimatedImageMode.UNRECOGNIZED;
}

/** In which quality to send videos. Maps to https://mediabunny.dev/api/Quality */
export const MediaSettings_VideoQuality = { LOW: 0, MEDIUM: 1, HIGH: 2, UNRECOGNIZED: -1 } as const;

export type MediaSettings_VideoQuality = typeof MediaSettings_VideoQuality[keyof typeof MediaSettings_VideoQuality];

export namespace MediaSettings_VideoQuality {
  export type LOW = typeof MediaSettings_VideoQuality.LOW;
  export type MEDIUM = typeof MediaSettings_VideoQuality.MEDIUM;
  export type HIGH = typeof MediaSettings_VideoQuality.HIGH;
  export type UNRECOGNIZED = typeof MediaSettings_VideoQuality.UNRECOGNIZED;
}

/**
 * Whether or not to automatically download file and media content for
 * incoming messages.
 */
export interface MediaSettings_AutoDownload {
  policy?: { $case: "off"; off: Unit } | { $case: "on"; on: MediaSettings_AutoDownload_AutoDownloadOn } | undefined;
}

export interface MediaSettings_AutoDownload_AutoDownloadOn {
  on:
    | Unit
    | undefined;
  /** If 0: No limit */
  limitInMb: number;
}

export interface ChatSettings {
  composeBarEnterMode?: ChatSettings_ComposeBarEnterMode | undefined;
}

export const ChatSettings_ComposeBarEnterMode = { SUBMIT: 0, LINE_BREAK: 1, UNRECOGNIZED: -1 } as const;

export type ChatSettings_ComposeBarEnterMode =
  typeof ChatSettings_ComposeBarEnterMode[keyof typeof ChatSettings_ComposeBarEnterMode];

export namespace ChatSettings_ComposeBarEnterMode {
  export type SUBMIT = typeof ChatSettings_ComposeBarEnterMode.SUBMIT;
  export type LINE_BREAK = typeof ChatSettings_ComposeBarEnterMode.LINE_BREAK;
  export type UNRECOGNIZED = typeof ChatSettings_ComposeBarEnterMode.UNRECOGNIZED;
}

/** Troubleshooting Settings */
export interface TroubleshootingSettings {
  callStatisticsPolicy?: TroubleshootingSettings_CallStatisticsPolicy | undefined;
}

/** Policy for recording of WebRTC call statistics (rtcstats) on this device */
export const TroubleshootingSettings_CallStatisticsPolicy = {
  /** DENY_RECORDING - Don't record call statistics */
  DENY_RECORDING: 0,
  /** RECORD_LOCALLY - Record call statistics into a local database */
  RECORD_LOCALLY: 1,
  UNRECOGNIZED: -1,
} as const;

export type TroubleshootingSettings_CallStatisticsPolicy =
  typeof TroubleshootingSettings_CallStatisticsPolicy[keyof typeof TroubleshootingSettings_CallStatisticsPolicy];

export namespace TroubleshootingSettings_CallStatisticsPolicy {
  export type DENY_RECORDING = typeof TroubleshootingSettings_CallStatisticsPolicy.DENY_RECORDING;
  export type RECORD_LOCALLY = typeof TroubleshootingSettings_CallStatisticsPolicy.RECORD_LOCALLY;
  export type UNRECOGNIZED = typeof TroubleshootingSettings_CallStatisticsPolicy.UNRECOGNIZED;
}

/** Work Settings */
export interface WorkSettings {
  /** Logos to be displayed in the app. */
  logo:
    | WorkSettings_ThemedLogos
    | undefined;
  /** The name of the organisation. */
  orgName?:
    | string
    | undefined;
  /** Custom in-app support base URL. */
  support?:
    | string
    | undefined;
  /**
   * A map of MDM parameters, originating from Threema App Configuration. The
   * map key is the identifier of the MDM parameter (e.g. `th_nickname`).
   */
  threemaMdmParameters: { [key: string]: WorkSettings_MdmParameter };
}

/** A single MDM parameter. */
export interface WorkSettings_MdmParameter {
  value?:
    | //
    /** String parameter */
    { $case: "stringValue"; stringValue: string }
    | //
    /** Integer parameter */
    { $case: "integerValue"; integerValue: Long }
    | //
    /** Boolean parameter */
    { $case: "booleanValue"; booleanValue: boolean }
    | undefined;
}

export interface WorkSettings_Logo {
  /** URL pointing a logo. */
  url: string;
  /** The logo as blob. */
  blob: Uint8Array;
}

export interface WorkSettings_ThemedLogos {
  light?: WorkSettings_Logo | undefined;
  dark?: WorkSettings_Logo | undefined;
}

export interface WorkSettings_ThreemaMdmParametersEntry {
  key: string;
  value: WorkSettings_MdmParameter | undefined;
}

function createBaseUnit(): Unit {
  return {};
}

export const Unit: MessageFns<Unit> = {
  encode(_: Unit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Unit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseIdentities(): Identities {
  return { identities: [] };
}

export const Identities: MessageFns<Identities> = {
  encode(message: Identities, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.identities) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Identities {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIdentities();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.identities.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseProfileSettings(): ProfileSettings {
  return {
    nickname: undefined,
    profilePictureBlob: undefined,
    profilePictureBlobId: undefined,
    profilePictureLastUploadedAt: undefined,
    profilePictureKey: undefined,
    profilePictureShareWith: undefined,
    workAvailabilityStatus: undefined,
  };
}

export const ProfileSettings: MessageFns<ProfileSettings> = {
  encode(message: ProfileSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nickname !== undefined) {
      writer.uint32(10).string(message.nickname);
    }
    if (message.profilePictureBlob !== undefined) {
      writer.uint32(18).bytes(message.profilePictureBlob);
    }
    if (message.profilePictureBlobId !== undefined) {
      writer.uint32(34).bytes(message.profilePictureBlobId);
    }
    if (message.profilePictureLastUploadedAt !== undefined) {
      writer.uint32(40).uint64(message.profilePictureLastUploadedAt.toString());
    }
    if (message.profilePictureKey !== undefined) {
      writer.uint32(50).bytes(message.profilePictureKey);
    }
    if (message.profilePictureShareWith !== undefined) {
      ProfileSettings_ProfilePictureShareWith.encode(message.profilePictureShareWith, writer.uint32(26).fork()).join();
    }
    if (message.workAvailabilityStatus !== undefined) {
      ProfileSettings_WorkAvailabilityStatus.encode(message.workAvailabilityStatus, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProfileSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProfileSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nickname = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.profilePictureBlob = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.profilePictureBlobId = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.profilePictureLastUploadedAt = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.profilePictureKey = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.profilePictureShareWith = ProfileSettings_ProfilePictureShareWith.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.workAvailabilityStatus = ProfileSettings_WorkAvailabilityStatus.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseProfileSettings_ProfilePictureShareWith(): ProfileSettings_ProfilePictureShareWith {
  return { policy: undefined };
}

export const ProfileSettings_ProfilePictureShareWith: MessageFns<ProfileSettings_ProfilePictureShareWith> = {
  encode(message: ProfileSettings_ProfilePictureShareWith, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.policy?.$case) {
      case "nobody":
        Unit.encode(message.policy.nobody, writer.uint32(10).fork()).join();
        break;
      case "everyone":
        Unit.encode(message.policy.everyone, writer.uint32(18).fork()).join();
        break;
      case "allowList":
        Identities.encode(message.policy.allowList, writer.uint32(26).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProfileSettings_ProfilePictureShareWith {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProfileSettings_ProfilePictureShareWith();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.policy = { $case: "nobody", nobody: Unit.decode(reader, reader.uint32()) };
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.policy = { $case: "everyone", everyone: Unit.decode(reader, reader.uint32()) };
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.policy = { $case: "allowList", allowList: Identities.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseProfileSettings_WorkAvailabilityStatus(): ProfileSettings_WorkAvailabilityStatus {
  return { category: 0, description: undefined };
}

export const ProfileSettings_WorkAvailabilityStatus: MessageFns<ProfileSettings_WorkAvailabilityStatus> = {
  encode(message: ProfileSettings_WorkAvailabilityStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.category !== 0) {
      writer.uint32(8).int32(message.category);
    }
    if (message.description !== undefined) {
      writer.uint32(18).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProfileSettings_WorkAvailabilityStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProfileSettings_WorkAvailabilityStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.category = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBasePrivacySettings(): PrivacySettings {
  return {
    contactSyncPolicy: undefined,
    unknownContactPolicy: undefined,
    readReceiptPolicy: undefined,
    typingIndicatorPolicy: undefined,
    screenshotPolicy: undefined,
    keyboardDataCollectionPolicy: undefined,
    blockedIdentities: undefined,
    excludeFromSyncIdentities: undefined,
  };
}

export const PrivacySettings: MessageFns<PrivacySettings> = {
  encode(message: PrivacySettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.contactSyncPolicy !== undefined) {
      writer.uint32(8).int32(message.contactSyncPolicy);
    }
    if (message.unknownContactPolicy !== undefined) {
      writer.uint32(16).int32(message.unknownContactPolicy);
    }
    if (message.readReceiptPolicy !== undefined) {
      writer.uint32(24).int32(message.readReceiptPolicy);
    }
    if (message.typingIndicatorPolicy !== undefined) {
      writer.uint32(32).int32(message.typingIndicatorPolicy);
    }
    if (message.screenshotPolicy !== undefined) {
      writer.uint32(40).int32(message.screenshotPolicy);
    }
    if (message.keyboardDataCollectionPolicy !== undefined) {
      writer.uint32(48).int32(message.keyboardDataCollectionPolicy);
    }
    if (message.blockedIdentities !== undefined) {
      Identities.encode(message.blockedIdentities, writer.uint32(58).fork()).join();
    }
    if (message.excludeFromSyncIdentities !== undefined) {
      Identities.encode(message.excludeFromSyncIdentities, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PrivacySettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePrivacySettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.contactSyncPolicy = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.unknownContactPolicy = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.readReceiptPolicy = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.typingIndicatorPolicy = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.screenshotPolicy = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.keyboardDataCollectionPolicy = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.blockedIdentities = Identities.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.excludeFromSyncIdentities = Identities.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCallsSettings(): CallsSettings {
  return {
    o2oCallPolicy: undefined,
    o2oCallConnectionPolicy: undefined,
    groupCallPolicy: undefined,
    lastSelectedCamera: undefined,
    lastSelectedMicrophone: undefined,
    lastSelectedSpeakers: undefined,
  };
}

export const CallsSettings: MessageFns<CallsSettings> = {
  encode(message: CallsSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.o2oCallPolicy !== undefined) {
      writer.uint32(8).int32(message.o2oCallPolicy);
    }
    if (message.o2oCallConnectionPolicy !== undefined) {
      writer.uint32(16).int32(message.o2oCallConnectionPolicy);
    }
    if (message.groupCallPolicy !== undefined) {
      writer.uint32(24).int32(message.groupCallPolicy);
    }
    if (message.lastSelectedCamera !== undefined) {
      writer.uint32(34).string(message.lastSelectedCamera);
    }
    if (message.lastSelectedMicrophone !== undefined) {
      writer.uint32(42).string(message.lastSelectedMicrophone);
    }
    if (message.lastSelectedSpeakers !== undefined) {
      writer.uint32(50).string(message.lastSelectedSpeakers);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallsSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallsSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.o2oCallPolicy = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.o2oCallConnectionPolicy = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.groupCallPolicy = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.lastSelectedCamera = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.lastSelectedMicrophone = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.lastSelectedSpeakers = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDevicesSettings(): DevicesSettings {
  return { deviceName: undefined };
}

export const DevicesSettings: MessageFns<DevicesSettings> = {
  encode(message: DevicesSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deviceName !== undefined) {
      writer.uint32(10).string(message.deviceName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DevicesSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDevicesSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deviceName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAppearanceSettings(): AppearanceSettings {
  return { timeFormat: undefined, inactiveContactsPolicy: undefined };
}

export const AppearanceSettings: MessageFns<AppearanceSettings> = {
  encode(message: AppearanceSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timeFormat !== undefined) {
      writer.uint32(8).int32(message.timeFormat);
    }
    if (message.inactiveContactsPolicy !== undefined) {
      writer.uint32(16).int32(message.inactiveContactsPolicy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AppearanceSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAppearanceSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timeFormat = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.inactiveContactsPolicy = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMediaSettings(): MediaSettings {
  return { autoDownload: undefined, animatedImageMode: undefined, videoQuality: undefined };
}

export const MediaSettings: MessageFns<MediaSettings> = {
  encode(message: MediaSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.autoDownload !== undefined) {
      MediaSettings_AutoDownload.encode(message.autoDownload, writer.uint32(10).fork()).join();
    }
    if (message.animatedImageMode !== undefined) {
      writer.uint32(16).int32(message.animatedImageMode);
    }
    if (message.videoQuality !== undefined) {
      writer.uint32(24).int32(message.videoQuality);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.autoDownload = MediaSettings_AutoDownload.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.animatedImageMode = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.videoQuality = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMediaSettings_AutoDownload(): MediaSettings_AutoDownload {
  return { policy: undefined };
}

export const MediaSettings_AutoDownload: MessageFns<MediaSettings_AutoDownload> = {
  encode(message: MediaSettings_AutoDownload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.policy?.$case) {
      case "off":
        Unit.encode(message.policy.off, writer.uint32(10).fork()).join();
        break;
      case "on":
        MediaSettings_AutoDownload_AutoDownloadOn.encode(message.policy.on, writer.uint32(18).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaSettings_AutoDownload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaSettings_AutoDownload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.policy = { $case: "off", off: Unit.decode(reader, reader.uint32()) };
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.policy = {
            $case: "on",
            on: MediaSettings_AutoDownload_AutoDownloadOn.decode(reader, reader.uint32()),
          };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMediaSettings_AutoDownload_AutoDownloadOn(): MediaSettings_AutoDownload_AutoDownloadOn {
  return { on: undefined, limitInMb: 0 };
}

export const MediaSettings_AutoDownload_AutoDownloadOn: MessageFns<MediaSettings_AutoDownload_AutoDownloadOn> = {
  encode(message: MediaSettings_AutoDownload_AutoDownloadOn, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.on !== undefined) {
      Unit.encode(message.on, writer.uint32(10).fork()).join();
    }
    if (message.limitInMb !== 0) {
      writer.uint32(16).uint32(message.limitInMb);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaSettings_AutoDownload_AutoDownloadOn {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaSettings_AutoDownload_AutoDownloadOn();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.on = Unit.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limitInMb = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseChatSettings(): ChatSettings {
  return { composeBarEnterMode: undefined };
}

export const ChatSettings: MessageFns<ChatSettings> = {
  encode(message: ChatSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.composeBarEnterMode !== undefined) {
      writer.uint32(8).int32(message.composeBarEnterMode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.composeBarEnterMode = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseTroubleshootingSettings(): TroubleshootingSettings {
  return { callStatisticsPolicy: undefined };
}

export const TroubleshootingSettings: MessageFns<TroubleshootingSettings> = {
  encode(message: TroubleshootingSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callStatisticsPolicy !== undefined) {
      writer.uint32(8).int32(message.callStatisticsPolicy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TroubleshootingSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTroubleshootingSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.callStatisticsPolicy = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseWorkSettings(): WorkSettings {
  return { logo: undefined, orgName: undefined, support: undefined, threemaMdmParameters: {} };
}

export const WorkSettings: MessageFns<WorkSettings> = {
  encode(message: WorkSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.logo !== undefined) {
      WorkSettings_ThemedLogos.encode(message.logo, writer.uint32(10).fork()).join();
    }
    if (message.orgName !== undefined) {
      writer.uint32(18).string(message.orgName);
    }
    if (message.support !== undefined) {
      writer.uint32(26).string(message.support);
    }
    Object.entries(message.threemaMdmParameters).forEach(([key, value]) => {
      WorkSettings_ThreemaMdmParametersEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.logo = WorkSettings_ThemedLogos.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.support = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = WorkSettings_ThreemaMdmParametersEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.threemaMdmParameters[entry4.key] = entry4.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseWorkSettings_MdmParameter(): WorkSettings_MdmParameter {
  return { value: undefined };
}

export const WorkSettings_MdmParameter: MessageFns<WorkSettings_MdmParameter> = {
  encode(message: WorkSettings_MdmParameter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.value?.$case) {
      case "stringValue":
        writer.uint32(10).string(message.value.stringValue);
        break;
      case "integerValue":
        writer.uint32(24).uint64(message.value.integerValue.toString());
        break;
      case "booleanValue":
        writer.uint32(16).bool(message.value.booleanValue);
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkSettings_MdmParameter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkSettings_MdmParameter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = { $case: "stringValue", stringValue: reader.string() };
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.value = { $case: "integerValue", integerValue: Long.fromString(reader.uint64().toString(), true) };
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = { $case: "booleanValue", booleanValue: reader.bool() };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseWorkSettings_Logo(): WorkSettings_Logo {
  return { url: "", blob: new Uint8Array(0) };
}

export const WorkSettings_Logo: MessageFns<WorkSettings_Logo> = {
  encode(message: WorkSettings_Logo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.url !== "") {
      writer.uint32(10).string(message.url);
    }
    if (message.blob.length !== 0) {
      writer.uint32(18).bytes(message.blob);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkSettings_Logo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkSettings_Logo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.blob = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseWorkSettings_ThemedLogos(): WorkSettings_ThemedLogos {
  return { light: undefined, dark: undefined };
}

export const WorkSettings_ThemedLogos: MessageFns<WorkSettings_ThemedLogos> = {
  encode(message: WorkSettings_ThemedLogos, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.light !== undefined) {
      WorkSettings_Logo.encode(message.light, writer.uint32(10).fork()).join();
    }
    if (message.dark !== undefined) {
      WorkSettings_Logo.encode(message.dark, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkSettings_ThemedLogos {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkSettings_ThemedLogos();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.light = WorkSettings_Logo.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.dark = WorkSettings_Logo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseWorkSettings_ThreemaMdmParametersEntry(): WorkSettings_ThreemaMdmParametersEntry {
  return { key: "", value: undefined };
}

export const WorkSettings_ThreemaMdmParametersEntry: MessageFns<WorkSettings_ThreemaMdmParametersEntry> = {
  encode(message: WorkSettings_ThreemaMdmParametersEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      WorkSettings_MdmParameter.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkSettings_ThreemaMdmParametersEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkSettings_ThreemaMdmParametersEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = WorkSettings_MdmParameter.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
