all: true
temp-dir: build/test-coverage-data
include:
  - src/**
exclude:
  - src/**/entry.ts
  - src/**/entry.*.ts
instrument: false
reporter:
  - html
report-dir: build/test-coverage-report
exclude-after-remp: false
