plugins:
  - '@prettier/plugin-xml'
  - 'prettier-plugin-svelte'

# Global rules
arrowParens: always
bracketSpacing: false
endOfLine: lf
printWidth: 100
proseWrap: always
quoteProps: consistent
singleQuote: true
tabWidth: 4

# Global svelte rules
svelteSortOrder: options-scripts-markup-styles

# Global XML rules
xmlWhitespaceSensitivity: preserve

# Overrides
overrides:
  - files: '*.{css,html,json,md,proto,scss,svelte,yml}'
    options:
      tabWidth: 2
  - files: '*.json'
    options:
      trailingComma: 'none'
  - files: '*.yml'
    options:
      # Preserve long lines that contain commands for readability
      proseWrap: preserve
  - files: '*.metainfo.xml'
    options:
      # Note: Only enable this for files that are whitespace-insensitive.
      xmlWhitespaceSensitivity: ignore
