// This file has been generated by structbuf. Do not modify it!
import * as base from '~/common/network/structbuf/base';
import type * as types from '~/common/types';
import * as utils from '../utils';

/**
 * ## Payload
 *
 * Once a path has been nominated, arbitrary payloads may be sent and
 * received. Any payloads are mandatory to encrypt and frame in form of a
 * `frame` struct.
 */

/**
 * Contains an encrypted message.
 *
 * Direction: RRD <-> RID
 */
export interface FrameLike {
    /**
     * Length of the `box` field.
     */
    readonly length: types.u32;

    /**
     * The message.
     *
     * For messages towards RRD, encrypted by:
     *
     *     Box(RK.secret)
     *       .encrypt(data=<message>, nonce=<RIDCK><RIDSN+>)
     *
     * For messages towards RID, encrypted by:
     *
     *     Box(RK.secret)
     *       .encrypt(data=<message>, nonce=<RRDCK><RRDSN+>)
     */
    readonly box: Uint8Array;
}

/**
 * Encodable of {@link FrameLike}.
 */
interface FrameEncodable_ {
    /**
     * 'box' field value or encoder. See {@link FrameLike#box} for
     * the field's description.
     */
    readonly box: Uint8Array | types.ByteLengthEncoder;
}

/**
 * New-type for FrameEncodable.
 */
export type FrameEncodable = types.WeakOpaque<
    FrameEncodable_,
    {readonly FrameEncodable: unique symbol}
>;

/** @inheritdoc */
export class Frame extends base.Struct implements FrameLike {
    private readonly _array: Uint8Array;
    private readonly _view: DataView;

    /**
     * Create a Frame from an array for accessing properties.
     *
     * Note: When accessing, attributes will be decoded on-the-fly which may be expensive.
     */
    private constructor(array: Uint8Array) {
        super();
        this._array = array;
        this._view = new DataView(array.buffer, array.byteOffset, array.byteLength);
    }

    /**
     * Decode a frame struct from an array.
     *
     * @param array Array to decode from.
     * @returns Frame instance.
     */
    public static decode(array: Uint8Array): Frame {
        return new Frame(array);
    }

    /**
     * Encode a frame struct into an array.
     *
     * @param struct FrameEncodable to encode.
     * @param array Array to encode into.
     * @returns A subarray of array containing the encoded struct.
     */
    public static encode(
        struct: types.EncoderPick<FrameEncodable, 'encode'>,
        array: Uint8Array,
    ): Uint8Array {
        const view = new DataView(array.buffer, array.byteOffset, array.byteLength);
        let offset = 4;

        // Encode `box`
        const lengthValue = utils.encodeBytes(struct.box, array, offset);
        offset += lengthValue;

        // Encode `length`
        view.setUint32(0, lengthValue, true);

        return array.subarray(0, offset);
    }

    /**
     * Get the amount of bytes that would be written when encoding a frame struct into an
     * array.
     *
     * @param struct FrameEncodable to encode.
     * @returns The amount of bytes that would be required to encode the struct.
     */
    public static byteLength(struct: types.EncoderPick<FrameEncodable, 'byteLength'>): types.u53 {
        let offset = 4;
        offset += utils.getByteLength(struct.box);
        return offset;
    }

    /**
     * 'length' field accessor. See {@link FrameLike#length} for the
     * field's description.
     */
    public get length(): types.u32 {
        return this._view.getUint32(0, true);
    }

    /**
     * 'box' field accessor. See {@link FrameLike#box} for the
     * field's description.
     */
    public get box(): Uint8Array {
        const offset = 4;
        return this._array.subarray(offset, offset + this.length);
    }

    /**
     * Create a snapshot of FrameLike.
     *
     * Note: This is **not** a deep-copy, so byte arrays will still be views of the underlying
     *       buffer.
     *
     * @returns FrameLike snapshot.
     */
    public snapshot(): FrameLike {
        return {
            length: this.length,
            box: this.box,
        };
    }

    /**
     * Create a clone of FrameLike.
     *
     * Note: This is a deep-copy that will copy the underlying buffer.
     *
     * @returns FrameLike clone.
     */
    public clone(): Frame {
        const array = new Uint8Array(this._array.byteLength);
        array.set(this._array);
        return new Frame(array);
    }
}
