// This file has been generated by structbuf. Do not modify it!
import * as crypto from './crypto';
import * as monitoring from './monitoring';
export {crypto, monitoring};

/**
 * # Extra Structures
 *
 * Structs defined here are not a mandatory part of any protocol but can be
 * used with any of them.
 */
