// This file has been generated by structbuf. Do not modify it!
import * as e2e from './e2e.js';
export {e2e};

/**
 * # Group Call Protocol (Supplementary)
 *
 * This is a supplementary section to the corresponding protobuf section with
 * messages that use structbuf instead of protobuf. All defined messages here
 * follow the same logic.
 */
