ALTER TABLE contacts ADD COLUMN colorIndex INTEGER NOT NULL DEFAULT 0;
ALTER TABLE groups ADD COLUMN colorIndex INTEGER NOT NULL DEFAULT 0;
ALTER TABLE distributionLists ADD COLUMN colorIndex INTEGER NOT NULL DEFAULT 0;

ALTER TABLE contacts DROP COLUMN cachedColor;
ALTER TABLE groups DROP COLUMN cachedColor;
