@startuml
!theme plain
title App Initialization
hide footbox

box Frontend #eff4fc
  participant App
  actor User
  participant BackendController
endbox
box Backend #fcf2ef
  participant Backend
  participant KeyStorage
  participant Database
endbox
box Network #f0fcef
  participant SafeServer
endbox

App->User:showLoadingScreen()
App->BackendController:create()
BackendController->Backend:create()

alt identity not found
  Backend->BackendController:Error(no-identity)

  BackendController->User:requestSafeBackupCredentials()
  BackendController->Backend:create(safeCredentials)
  Backend->SafeServer:download()
  alt electron
    Backend->KeyStorage:createKeyStorage(clientKey)
  end
  Backend->Database:createDatabase(essentialData)
else identity found
  alt electron
    Backend->KeyStorage:loadKeyStorage()
  end
  Backend->Database:loadDatabase()
end

App->User:showApplication()
@enduml
